package com.bugmaker.bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CheckIn generated by hbm2java
 */
@Entity
@Table(name="check_in"
    ,catalog="career_development"
)
public class CheckIn  implements java.io.Serializable {


     private String id;
     private String insId;
     private String stuId;
     private String state;
     private Date checkAm;
     private Date checkPm;

    public CheckIn() {
    }

	
    public CheckIn(String id) {
        this.id = id;
    }
    public CheckIn(String id, String insId, String stuId, String state, Date checkAm, Date checkPm) {
       this.id = id;
       this.insId = insId;
       this.stuId = stuId;
       this.state = state;
       this.checkAm = checkAm;
       this.checkPm = checkPm;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="ins_id", length=32)
    public String getInsId() {
        return this.insId;
    }
    
    public void setInsId(String insId) {
        this.insId = insId;
    }
    
    @Column(name="stu_id", length=32)
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="state", length=10)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="check_am", length=19)
    public Date getCheckAm() {
        return this.checkAm;
    }
    
    public void setCheckAm(Date checkAm) {
        this.checkAm = checkAm;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="check_pm", length=19)
    public Date getCheckPm() {
        return this.checkPm;
    }
    
    public void setCheckPm(Date checkPm) {
        this.checkPm = checkPm;
    }




}


