package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name="classroom"
    ,catalog="career_development"
)
public class Classroom  implements java.io.Serializable {


     private String id;
     private String name;
     private String deptId;
     private String direcId;

    public Classroom() {
    }

	
    public Classroom(String id) {
        this.id = id;
    }
    public Classroom(String id, String name, String deptId, String direcId) {
       this.id = id;
       this.name = name;
       this.deptId = deptId;
       this.direcId = direcId;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="dept_id", length=32)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }
    
    @Column(name="direc_id", length=32)
    public String getDirecId() {
        return this.direcId;
    }
    
    public void setDirecId(String direcId) {
        this.direcId = direcId;
    }




}


