package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name="company"
    ,catalog="career_development"
)
public class Company  implements java.io.Serializable {


     private String id;
     private String name;
     private String address;
     private String phone;
     private String advisor;

    public Company() {
    }

	
    public Company(String id) {
        this.id = id;
    }
    public Company(String id, String name, String address, String phone, String advisor) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.advisor = advisor;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="address", length=32)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="phone", length=11)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="advisor", length=10)
    public String getAdvisor() {
        return this.advisor;
    }
    
    public void setAdvisor(String advisor) {
        this.advisor = advisor;
    }




}


