package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Direction generated by hbm2java
 */
@Entity
@Table(name="direction"
    ,catalog="career_development"
)
public class Direction  implements java.io.Serializable {


     private String id;
     private String name;
     private String professId;
     private String describe;

    public Direction() {
    }

	
    public Direction(String id) {
        this.id = id;
    }
    public Direction(String id, String name, String professId, String describe) {
       this.id = id;
       this.name = name;
       this.professId = professId;
       this.describe = describe;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="profess_id", length=32)
    public String getProfessId() {
        return this.professId;
    }
    
    public void setProfessId(String professId) {
        this.professId = professId;
    }
    
    @Column(name="describe", length=32)
    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }




}


