package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InternshipDetail generated by hbm2java
 */
@Entity
@Table(name="internship_detail"
    ,catalog="career_development"
)
public class InternshipDetail  implements java.io.Serializable {


     private String id;
     private String stuId;
     private String insId;
     private String teacId;
     private String dormitory;

    public InternshipDetail() {
    }

	
    public InternshipDetail(String id) {
        this.id = id;
    }
    public InternshipDetail(String id, String stuId, String insId, String teacId, String dormitory) {
       this.id = id;
       this.stuId = stuId;
       this.insId = insId;
       this.teacId = teacId;
       this.dormitory = dormitory;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="stu_id", length=32)
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="ins_id", length=32)
    public String getInsId() {
        return this.insId;
    }
    
    public void setInsId(String insId) {
        this.insId = insId;
    }
    
    @Column(name="teac_id", length=32)
    public String getTeacId() {
        return this.teacId;
    }
    
    public void setTeacId(String teacId) {
        this.teacId = teacId;
    }
    
    @Column(name="dormitory", length=32)
    public String getDormitory() {
        return this.dormitory;
    }
    
    public void setDormitory(String dormitory) {
        this.dormitory = dormitory;
    }




}


