package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name="job"
    ,catalog="career_development"
)
public class Job  implements java.io.Serializable {


     private String id;
     private String companyId;
     private String name;
     private Double salary;
     private String outteacId;

    public Job() {
    }

	
    public Job(String id) {
        this.id = id;
    }
    public Job(String id, String companyId, String name, Double salary, String outteacId) {
       this.id = id;
       this.companyId = companyId;
       this.name = name;
       this.salary = salary;
       this.outteacId = outteacId;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="salary", precision=22, scale=0)
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    
    @Column(name="outteac_id", length=32)
    public String getOutteacId() {
        return this.outteacId;
    }
    
    public void setOutteacId(String outteacId) {
        this.outteacId = outteacId;
    }




}


