package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Outteacher generated by hbm2java
 */
@Entity
@Table(name="outteacher"
    ,catalog="career_development"
)
public class Outteacher  implements java.io.Serializable {


     private OutteacherId id;

    public Outteacher() {
    }

    public Outteacher(OutteacherId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false, length=32) ), 
        @AttributeOverride(name="companyId", column=@Column(name="company_id", length=32) ) } )
    public OutteacherId getId() {
        return this.id;
    }
    
    public void setId(OutteacherId id) {
        this.id = id;
    }




}


