package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OutteacherId generated by hbm2java
 */
@Embeddable
public class OutteacherId  implements java.io.Serializable {


     private String id;
     private String companyId;

    public OutteacherId() {
    }

	
    public OutteacherId(String id) {
        this.id = id;
    }
    public OutteacherId(String id, String companyId) {
       this.id = id;
       this.companyId = companyId;
    }
   

    @Column(name="id", nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OutteacherId) ) return false;
		 OutteacherId castOther = ( OutteacherId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
         return result;
   }   


}


