package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permiss generated by hbm2java
 */
@Entity
@Table(name="permiss"
    ,catalog="career_development"
)
public class Permiss  implements java.io.Serializable {


     private String id;
     private String parentId;
     private String url;
     private String describe;

    public Permiss() {
    }

	
    public Permiss(String id) {
        this.id = id;
    }
    public Permiss(String id, String parentId, String url, String describe) {
       this.id = id;
       this.parentId = parentId;
       this.url = url;
       this.describe = describe;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="parent_id", length=32)
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="url", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="describe", length=32)
    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }




}


