package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profession generated by hbm2java
 */
@Entity
@Table(name="profession"
    ,catalog="career_development"
)
public class Profession  implements java.io.Serializable {


     private String id;
     private String name;
     private String describe;
     private String deptId;

    public Profession() {
    }

	
    public Profession(String id) {
        this.id = id;
    }
    public Profession(String id, String name, String describe, String deptId) {
       this.id = id;
       this.name = name;
       this.describe = describe;
       this.deptId = deptId;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="describe", length=32)
    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }
    
    @Column(name="dept_id", length=32)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }




}


