package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfessVolunteer generated by hbm2java
 */
@Entity
@Table(name="profess_volunteer"
    ,catalog="career_development"
)
public class ProfessVolunteer  implements java.io.Serializable {


     private String id;
     private String stuId;
     private String direcId1;
     private String direcId2;
     private String direcId3;

    public ProfessVolunteer() {
    }

	
    public ProfessVolunteer(String id) {
        this.id = id;
    }
    public ProfessVolunteer(String id, String stuId, String direcId1, String direcId2, String direcId3) {
       this.id = id;
       this.stuId = stuId;
       this.direcId1 = direcId1;
       this.direcId2 = direcId2;
       this.direcId3 = direcId3;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="stu_id", length=32)
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="direc_id1", length=32)
    public String getDirecId1() {
        return this.direcId1;
    }
    
    public void setDirecId1(String direcId1) {
        this.direcId1 = direcId1;
    }
    
    @Column(name="direc_id2", length=32)
    public String getDirecId2() {
        return this.direcId2;
    }
    
    public void setDirecId2(String direcId2) {
        this.direcId2 = direcId2;
    }
    
    @Column(name="direc_id3", length=32)
    public String getDirecId3() {
        return this.direcId3;
    }
    
    public void setDirecId3(String direcId3) {
        this.direcId3 = direcId3;
    }




}


