package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Protocol generated by hbm2java
 */
@Entity
@Table(name="protocol"
    ,catalog="career_development"
)
public class Protocol  implements java.io.Serializable {


     private String id;
     private String safeProtocal;
     private String internshipRecord;
     private String acceptProve;
     private String internshipAssess;
     private String report;
     private String internshipApplication;
     private Integer stuId;
     private String type;

    public Protocol() {
    }

	
    public Protocol(String id) {
        this.id = id;
    }
    public Protocol(String id, String safeProtocal, String internshipRecord, String acceptProve, String internshipAssess, String report, String internshipApplication, Integer stuId, String type) {
       this.id = id;
       this.safeProtocal = safeProtocal;
       this.internshipRecord = internshipRecord;
       this.acceptProve = acceptProve;
       this.internshipAssess = internshipAssess;
       this.report = report;
       this.internshipApplication = internshipApplication;
       this.stuId = stuId;
       this.type = type;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="safe_protocal", length=32)
    public String getSafeProtocal() {
        return this.safeProtocal;
    }
    
    public void setSafeProtocal(String safeProtocal) {
        this.safeProtocal = safeProtocal;
    }
    
    @Column(name="internship_record", length=32)
    public String getInternshipRecord() {
        return this.internshipRecord;
    }
    
    public void setInternshipRecord(String internshipRecord) {
        this.internshipRecord = internshipRecord;
    }
    
    @Column(name="accept_prove", length=32)
    public String getAcceptProve() {
        return this.acceptProve;
    }
    
    public void setAcceptProve(String acceptProve) {
        this.acceptProve = acceptProve;
    }
    
    @Column(name="internship_assess", length=32)
    public String getInternshipAssess() {
        return this.internshipAssess;
    }
    
    public void setInternshipAssess(String internshipAssess) {
        this.internshipAssess = internshipAssess;
    }
    
    @Column(name="report", length=32)
    public String getReport() {
        return this.report;
    }
    
    public void setReport(String report) {
        this.report = report;
    }
    
    @Column(name="internship_application", length=32)
    public String getInternshipApplication() {
        return this.internshipApplication;
    }
    
    public void setInternshipApplication(String internshipApplication) {
        this.internshipApplication = internshipApplication;
    }
    
    @Column(name="stu_id")
    public Integer getStuId() {
        return this.stuId;
    }
    
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="type", length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


