package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="career_development"
)
public class Role  implements java.io.Serializable {


     private String id;
     private String roleName;
     private String rolePermiss;

    public Role() {
    }

	
    public Role(String id) {
        this.id = id;
    }
    public Role(String id, String roleName, String rolePermiss) {
       this.id = id;
       this.roleName = roleName;
       this.rolePermiss = rolePermiss;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="role_name", length=10)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
    @Column(name="role_permiss", length=100)
    public String getRolePermiss() {
        return this.rolePermiss;
    }
    
    public void setRolePermiss(String rolePermiss) {
        this.rolePermiss = rolePermiss;
    }




}


