package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RolePermiss generated by hbm2java
 */
@Entity
@Table(name="role_permiss"
    ,catalog="career_development"
)
public class RolePermiss  implements java.io.Serializable {


     private String id;
     private String roleId;
     private String permissId;

    public RolePermiss() {
    }

	
    public RolePermiss(String id) {
        this.id = id;
    }
    public RolePermiss(String id, String roleId, String permissId) {
       this.id = id;
       this.roleId = roleId;
       this.permissId = permissId;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="role_id", length=32)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="permiss_id", length=32)
    public String getPermissId() {
        return this.permissId;
    }
    
    public void setPermissId(String permissId) {
        this.permissId = permissId;
    }




}


