package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Score generated by hbm2java
 */
@Entity
@Table(name="score"
    ,catalog="career_development"
)
public class Score  implements java.io.Serializable {


     private String id;
     private String stuId;
     private String teacId;
     private Double teacScore;
     private Double outteacScore;
     private Integer no;

    public Score() {
    }

	
    public Score(String id) {
        this.id = id;
    }
    public Score(String id, String stuId, String teacId, Double teacScore, Double outteacScore, Integer no) {
       this.id = id;
       this.stuId = stuId;
       this.teacId = teacId;
       this.teacScore = teacScore;
       this.outteacScore = outteacScore;
       this.no = no;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="stu_id", length=32)
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="teac_id", length=32)
    public String getTeacId() {
        return this.teacId;
    }
    
    public void setTeacId(String teacId) {
        this.teacId = teacId;
    }
    
    @Column(name="teac_score", precision=22, scale=0)
    public Double getTeacScore() {
        return this.teacScore;
    }
    
    public void setTeacScore(Double teacScore) {
        this.teacScore = teacScore;
    }
    
    @Column(name="outteac_score", precision=22, scale=0)
    public Double getOutteacScore() {
        return this.outteacScore;
    }
    
    public void setOutteacScore(Double outteacScore) {
        this.outteacScore = outteacScore;
    }
    
    @Column(name="no")
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }




}


