package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StuLog generated by hbm2java
 */
@Entity
@Table(name="stu_log"
    ,catalog="career_development"
)
public class StuLog  implements java.io.Serializable {


     private String id;
     private String stuId;
     private String content;
     private Date writeDate;
     private String teacId;
     private String schoolTeacWriteback;
     private String schoolTeacSign;
     private Date schoolWritebackDate;
     private String outSchoolTeacWriteback;
     private String outSchoolTeacSign;
     private Date outSchoolWritebackDate;

    public StuLog() {
    }

	
    public StuLog(String id) {
        this.id = id;
    }
    public StuLog(String id, String stuId, String content, Date writeDate, String teacId, String schoolTeacWriteback, String schoolTeacSign, Date schoolWritebackDate, String outSchoolTeacWriteback, String outSchoolTeacSign, Date outSchoolWritebackDate) {
       this.id = id;
       this.stuId = stuId;
       this.content = content;
       this.writeDate = writeDate;
       this.teacId = teacId;
       this.schoolTeacWriteback = schoolTeacWriteback;
       this.schoolTeacSign = schoolTeacSign;
       this.schoolWritebackDate = schoolWritebackDate;
       this.outSchoolTeacWriteback = outSchoolTeacWriteback;
       this.outSchoolTeacSign = outSchoolTeacSign;
       this.outSchoolWritebackDate = outSchoolWritebackDate;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="stu_id", length=32)
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="write_date", length=19)
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    
    @Column(name="teac_id", length=32)
    public String getTeacId() {
        return this.teacId;
    }
    
    public void setTeacId(String teacId) {
        this.teacId = teacId;
    }
    
    @Column(name="school_teac_writeback", length=32)
    public String getSchoolTeacWriteback() {
        return this.schoolTeacWriteback;
    }
    
    public void setSchoolTeacWriteback(String schoolTeacWriteback) {
        this.schoolTeacWriteback = schoolTeacWriteback;
    }
    
    @Column(name="school_teac_sign", length=32)
    public String getSchoolTeacSign() {
        return this.schoolTeacSign;
    }
    
    public void setSchoolTeacSign(String schoolTeacSign) {
        this.schoolTeacSign = schoolTeacSign;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="school_writeback_date", length=19)
    public Date getSchoolWritebackDate() {
        return this.schoolWritebackDate;
    }
    
    public void setSchoolWritebackDate(Date schoolWritebackDate) {
        this.schoolWritebackDate = schoolWritebackDate;
    }
    
    @Column(name="out_school_teac_writeback", length=32)
    public String getOutSchoolTeacWriteback() {
        return this.outSchoolTeacWriteback;
    }
    
    public void setOutSchoolTeacWriteback(String outSchoolTeacWriteback) {
        this.outSchoolTeacWriteback = outSchoolTeacWriteback;
    }
    
    @Column(name="out_school_teac_sign", length=32)
    public String getOutSchoolTeacSign() {
        return this.outSchoolTeacSign;
    }
    
    public void setOutSchoolTeacSign(String outSchoolTeacSign) {
        this.outSchoolTeacSign = outSchoolTeacSign;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="out_school_writeback_date", length=19)
    public Date getOutSchoolWritebackDate() {
        return this.outSchoolWritebackDate;
    }
    
    public void setOutSchoolWritebackDate(Date outSchoolWritebackDate) {
        this.outSchoolWritebackDate = outSchoolWritebackDate;
    }




}


