package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name="survey"
    ,catalog="career_development"
)
public class Survey  implements java.io.Serializable {


     private String id;
     private String stuId;
     private String professName;
     private String unitName;
     private String unitPerson;
     private String unitPhone;
     private String stuPhone;
     private String status;
     private String situation;

    public Survey() {
    }

	
    public Survey(String id) {
        this.id = id;
    }
    public Survey(String id, String stuId, String professName, String unitName, String unitPerson, String unitPhone, String stuPhone, String status, String situation) {
       this.id = id;
       this.stuId = stuId;
       this.professName = professName;
       this.unitName = unitName;
       this.unitPerson = unitPerson;
       this.unitPhone = unitPhone;
       this.stuPhone = stuPhone;
       this.status = status;
       this.situation = situation;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="stu_id", length=32)
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    
    @Column(name="profess_name", length=32)
    public String getProfessName() {
        return this.professName;
    }
    
    public void setProfessName(String professName) {
        this.professName = professName;
    }
    
    @Column(name="unit_name", length=32)
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    
    @Column(name="unit_person", length=10)
    public String getUnitPerson() {
        return this.unitPerson;
    }
    
    public void setUnitPerson(String unitPerson) {
        this.unitPerson = unitPerson;
    }
    
    @Column(name="unit_phone", length=11)
    public String getUnitPhone() {
        return this.unitPhone;
    }
    
    public void setUnitPhone(String unitPhone) {
        this.unitPhone = unitPhone;
    }
    
    @Column(name="stu_phone", length=11)
    public String getStuPhone() {
        return this.stuPhone;
    }
    
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone;
    }
    
    @Column(name="status", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="situation", length=10)
    public String getSituation() {
        return this.situation;
    }
    
    public void setSituation(String situation) {
        this.situation = situation;
    }




}


