package bean;
// Generated 2017-9-13 8:41:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="career_development"
)
public class User  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private Integer sex;
     private Integer age;
     private String phone;
     private String email;
     private Integer enable;
     private Integer type;
     private String roleId;
     private String deptId;
     private Date creatTime;

    public User() {
    }

	
    public User(String id) {
        this.id = id;
    }
    public User(String id, String username, String password, Integer sex, Integer age, String phone, String email, Integer enable, Integer type, String roleId, String deptId, Date creatTime) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.sex = sex;
       this.age = age;
       this.phone = phone;
       this.email = email;
       this.enable = enable;
       this.type = type;
       this.roleId = roleId;
       this.deptId = deptId;
       this.creatTime = creatTime;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="username", length=10)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="sex")
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
    @Column(name="phone", length=11)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="enable")
    public Integer getEnable() {
        return this.enable;
    }
    
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    
    @Column(name="role_id", length=32)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="dept_id", length=32)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creat_time", length=19)
    public Date getCreatTime() {
        return this.creatTime;
    }
    
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }




}


